import Head from 'next/head';
import { Wrapper, Status } from "@googlemaps/react-wrapper";
import Map from '../components/Map';
import { Tab } from '@headlessui/react'
import { useState } from 'react';

function classNames(...classes) {
    return classes.filter(Boolean).join(' ')
}

export default function Home({ sheds }) {
    const [categories] = useState(['Octane 92', 'Octane 95', 'Diesel', 'Super Diesel', 'Kerosene'])
    const [selectedCategory, setSelectedCategory] = useState(0)
    const [minOil, setMinOil] = useState(200)

    const center = { lat: 7.867373, lng: 80.800702 };
    const zoom = 8;

    function render(status) {
        if (status === Status.LOADING) return <h3>{status} ..</h3>;
        if (status === Status.FAILURE) return <h3>{status} ...</h3>;
        return null;
    }
    function handleMinOil(event) {
        setMinOil(event.target.value)
    }

    return (
        <>
            <Head>
                <title>Fuel</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
                <link rel="icon" href="/gas-station.svg" />
            </Head>

            <Wrapper apiKey={"AIzaSyBnPWI3aKEk5Nj-WJhnnDlJcRWmppMVI2E"} render={render} libraries={['visualization']}>
                <Map center={center} zoom={zoom} sheds={sheds} selectedCategory={selectedCategory} minOil={minOil} />
            </Wrapper>

            <div className="fixed -top-14 right-0 w-full max-w-md px-1 py-16">
                <Tab.Group
                    onChange={(index) => {
                        setSelectedCategory(index)
                    }}
                >
                    <Tab.List className="flex space-x-1 rounded-xl bg-blue-900/20 p-1">
                        {categories.map((category) => (
                            <Tab
                                key={category}
                                className={({ selected }) =>
                                    classNames(
                                        'w-full rounded-lg py-2 text-sm font-medium leading-5 text-blue-700 px-[1px]',
                                        'focus:outline-none',
                                        selected
                                            ? 'bg-white shadow'
                                            : 'text-blue-100 hover:bg-white/[0.12] hover:text-white'
                                    )
                                }
                            >
                                {category}
                            </Tab>
                        ))}
                    </Tab.List>
                </Tab.Group>
                <div className="mt-1 flex items-center cursor-default overflow-hidden text-sm rounded-lg bg-blue-900/20 text-left shadow-md">
                    <span className="shrink-0 text-white text-xs mx-2 font-medium">
                        Min. available {categories[selectedCategory]} liters in a shed
                    </span>
                    <input
                        value={minOil}
                        onChange={handleMinOil}
                        onKeyDown={(event) => {
                            if (event.key !== 'Backspace') {
                                if (!/[0-9]/.test(event.key)) {
                                    event.preventDefault();
                                }
                            }
                        }}
                        className="text-blue-700 w-full border-none py-2 pl-3 pr-10 text-sm leading-5 focus:ring-0" />
                </div>
            </div>

        </>
    )
}

export async function getServerSideProps() {
    const dev = true
    const server = dev ? 'http://localhost:3000' : 'https://fuel-git-main-nova9.vercel.app'
    // const response = await fetch(`${server}/api/sheds`)
    const response = await fetch('https://raw.githubusercontent.com/nova9/fuel/main/latest.json?token=GHSAT0AAAAAABSTAFTEEHQH2ZZIABSJAXFUYVMMG6A')
    const sheds = await response.json()

    return { props: { sheds } }
}